### PR TITLE
ES optimized content indexing

### PR DESCRIPTION
**Pull request by Jihed525**
This Doc update is related to [Optimize indexed file contents in Elastic search](https://github.com/exodev/ecms/pull/704) improvement

### CODE REVIEW

**Review by ahamdi — CHANGES_REQUESTED** [review]
Could you add those properties to the list of properties in https://docs.exoplatform.org/en/6.0/Configuration.html

**Comment by Jihed525** [comment]
> Could you add those properties to the list of properties in https://docs.exoplatform.org/en/6.0/Configuration.html

Added in [PR](https://github.com/exoplatform/exo-documentation/pull/279)

**Comment by ahamdi** [comment]
Please reference the added properties in this documentation from the Properties reference page

**Comment by Jihed525** [comment]
> Please reference the added properties in this documentation from the Properties reference page

Done, is it ok ?

**Review by ahamdi — APPROVED** [review]
LGTM

**Pull request merged**
